### ISSUE TITLE
Process hangs at startup when C* node not joined

### ISSUE THREAD

**Issue by etedpet** [Ericsson/ecchronos#190]
When scaling out a C* cluster with a lot of data, adding a new node takes some time (C* state/status - UJ).
After some time (_connection.cql.timeout_ config?) the following exception is logged and then the process hangs.

```
[org.springframework.boot.SpringApplication] Application run failed org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ECChronos' defined in URL [jar:file:/usr/share/ecchronos/lib/application-2.0.0.jar!/com/ericsson/bss/cassandra/ecchronos/application/spring/ECChronos.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nativeConnectionProvider' defined in class path resource [com/ericsson/bss/cassandra/ecchronos/application/spring/BeanConfigurator.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ericsson.bss.cassandra.ecchronos.connection.NativeConnectionProvider]: Factory method 'nativeConnectionProvider' threw exception; nested exception is com.ericsson.bss.cassandra.ecchronos.application.ConfigurationException: Unable to construct class com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.SpringBooter.main(SpringBooter.java:29)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nativeConnectionProvider' defined in class path resource [com/ericsson/bss/cassandra/ecchronos/application/spring/BeanConfigurator.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ericsson.bss.cassandra.ecchronos.connection.NativeConnectionProvider]: Factory method 'nativeConnectionProvider' threw exception; nested exception is com.ericsson.bss.cassandra.ecchronos.application.ConfigurationException: Unable to construct class com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 20 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ericsson.bss.cassandra.ecchronos.connection.NativeConnectionProvider]: Factory method 'nativeConnectionProvider' threw exception; nested exception is com.ericsson.bss.cassandra.ecchronos.application.ConfigurationException: Unable to construct class com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 34 common frames omitted
Caused by: com.ericsson.bss.cassandra.ecchronos.application.ConfigurationException: Unable to construct class com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider
	at com.ericsson.bss.cassandra.ecchronos.application.ReflectionUtils.construct(ReflectionUtils.java:61)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.BeanConfigurator.getNativeConnectionProvider(BeanConfigurator.java:136)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.BeanConfigurator.nativeConnectionProvider(BeanConfigurator.java:128)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.BeanConfigurator$$EnhancerBySpringCGLIB$$1b9f3046.CGLIB$nativeConnectionProvider$6(<generated>)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.BeanConfigurator$$EnhancerBySpringCGLIB$$1b9f3046$$FastClassBySpringCGLIB$$6bdc1997.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.BeanConfigurator$$EnhancerBySpringCGLIB$$1b9f3046.nativeConnectionProvider(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 35 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.ericsson.bss.cassandra.ecchronos.application.ReflectionUtils.construct(ReflectionUtils.java:57)
	... 47 common frames omitted
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: wcdbcd-3.wcdbcd/192.168.198.163:9042 (com.datastax.driver.core.exceptions.TransportException: [wcdbcd-3.wcdbcd/192.168.198.163:9042] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:270)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:109)
	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1813)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1726)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:462)
	at com.ericsson.bss.cassandra.ecchronos.connection.impl.LocalNativeConnectionProvider$Builder.resolveLocalDataCenter(LocalNativeConnectionProvider.java:143)
	at com.ericsson.bss.cassandra.ecchronos.connection.impl.LocalNativeConnectionProvider$Builder.createCluster(LocalNativeConnectionProvider.java:119)
	at com.ericsson.bss.cassandra.ecchronos.connection.impl.LocalNativeConnectionProvider$Builder.build(LocalNativeConnectionProvider.java:105)
	at com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider.establishConnection(DefaultNativeConnectionProvider.java:97)
	at com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider.<init>(DefaultNativeConnectionProvider.java:64)
	... 52 common frames omitted

```

**Comment by itskarlsson** [comment]
Testing in my small local cluster, timeout behaves normally. I added 25 seconds timeout. The process attempts to connect a few times before receiving the same error above and then exiting with exit code 1.

```
32950 [main] ERROR o.s.boot.SpringApplication - Application run failed 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ECChronos' defined in file [/home/ejankan/workspace/kchronos/application/target/classes/com/ericsson/bss/cassandra/ecchronos/application/spring/ECChronos.class]: Unsatisfied dependency expressed through constructor parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nativeConnectionProvider' defined in class path resource [com/ericsson/bss/cassandra/ecchronos/application/spring/BeanConfigurator.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ericsson.bss.cassandra.ecchronos.connection.NativeConnectionProvider]: Factory method 'nativeConnectionProvider' threw exception; nested exception is com.ericsson.bss.cassandra.ecchronos.application.ConfigurationException: Unable to construct class com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$176/332873513.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.SpringBooter.main(SpringBooter.java:29)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nativeConnectionProvider' defined in class path resource [com/ericsson/bss/cassandra/ecchronos/application/spring/BeanConfigurator.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ericsson.bss.cassandra.ecchronos.connection.NativeConnectionProvider]: Factory method 'nativeConnectionProvider' threw exception; nested exception is com.ericsson.bss.cassandra.ecchronos.application.ConfigurationException: Unable to construct class com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1334)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$176/332873513.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 21 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ericsson.bss.cassandra.ecchronos.connection.NativeConnectionProvider]: Factory method 'nativeConnectionProvider' threw exception; nested exception is com.ericsson.bss.cassandra.ecchronos.application.ConfigurationException: Unable to construct class com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 36 common frames omitted
Caused by: com.ericsson.bss.cassandra.ecchronos.application.ConfigurationException: Unable to construct class com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider
	at com.ericsson.bss.cassandra.ecchronos.application.ReflectionUtils.construct(ReflectionUtils.java:61)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.BeanConfigurator.getNativeConnectionProvider(BeanConfigurator.java:136)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.BeanConfigurator.nativeConnectionProvider(BeanConfigurator.java:128)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.BeanConfigurator$$EnhancerBySpringCGLIB$$ead56f5d.CGLIB$nativeConnectionProvider$3(<generated>)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.BeanConfigurator$$EnhancerBySpringCGLIB$$ead56f5d$$FastClassBySpringCGLIB$$976306c6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.ericsson.bss.cassandra.ecchronos.application.spring.BeanConfigurator$$EnhancerBySpringCGLIB$$ead56f5d.nativeConnectionProvider(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 37 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.ericsson.bss.cassandra.ecchronos.application.ReflectionUtils.construct(ReflectionUtils.java:57)
	... 49 common frames omitted
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:270)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:109)
	at com.datastax.driver.core.Cluster$Manager.negotiateProtocolVersionAndConnect(Cluster.java:1813)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1726)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:462)
	at com.ericsson.bss.cassandra.ecchronos.connection.impl.LocalNativeConnectionProvider$Builder.resolveLocalDataCenter(LocalNativeConnectionProvider.java:143)
	at com.ericsson.bss.cassandra.ecchronos.connection.impl.LocalNativeConnectionProvider$Builder.createCluster(LocalNativeConnectionProvider.java:119)
	at com.ericsson.bss.cassandra.ecchronos.connection.impl.LocalNativeConnectionProvider$Builder.build(LocalNativeConnectionProvider.java:105)
	at com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider.establishConnection(DefaultNativeConnectionProvider.java:97)
	at com.ericsson.bss.cassandra.ecchronos.application.DefaultNativeConnectionProvider.<init>(DefaultNativeConnectionProvider.java:64)
	... 54 common frames omitted

Process finished with exit code 1
```
In my test, I am not scaling out a cluster but merely turn off one node and try to connect to it. Please let me know if you have any ideas on how to reproduce this.

**Comment by itskarlsson** [comment]
Strangely, I was not able to reproduce through IDE, but able to reproduce it by running ecChronos binary. It seems that springboot doesn't handle exiting properly when it fails to create the default application context.
