### ISSUE TITLE
Schedules might never be created if there's an error at startup

### ISSUE THREAD

**Issue by masokol** [Ericsson/ecchronos#478]
I've stumbled upon a strange behavior.

To reproduce:

1. CCM cluster 4 nodes, 1 dc. Replication for ecchronos keyspace, dc1=1
2. Turn off node 4
3. Try to start ecchronos that is supposed to connect to node1
4. Observe stacktrace in log, also 1 schedule is missing. Ecchronos is running, it hasn't crashed.
5. Start node4
6. Still no schedule.

Stacktrace:

```
13:43:29.800 [RepairScheduler-0] ERROR c.e.b.c.e.c.r.RepairSchedulerImpl - Unexpected error during schedule change of test2.table1:
com.datastax.oss.driver.api.core.servererrors.UnavailableException: Not enough replicas available for query at consistency LOCAL_ONE (1 required but only 0 alive)
        at com.datastax.oss.driver.api.core.servererrors.UnavailableException.copy(UnavailableException.java:103)
        at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
        at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
        at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
        at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.state.EccRepairHistory.execute(EccRepairHistory.java:185)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.state.EccRepairHistory.iterate(EccRepairHistory.java:178)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.state.EccRepairHistory.iterate(EccRepairHistory.java:159)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.state.EccRepairHistory.iterate(EccRepairHistory.java:150)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.state.VnodeRepairStateFactoryImpl.calculateNewState(VnodeRepairStateFactoryImpl.java:67)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.state.RepairStateImpl.generateNewRepairState(RepairStateImpl.java:119)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.state.RepairStateImpl.update(RepairStateImpl.java:79)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.state.RepairStateImpl.<init>(RepairStateImpl.java:67)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.state.RepairStateFactoryImpl.create(RepairStateFactoryImpl.java:54)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.RepairSchedulerImpl.getRepairJob(RepairSchedulerImpl.java:211)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.RepairSchedulerImpl.createTableSchedule(RepairSchedulerImpl.java:170)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.RepairSchedulerImpl.handleTableConfigurationChange(RepairSchedulerImpl.java:145)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.RepairSchedulerImpl.lambda$putConfiguration$0(RepairSchedulerImpl.java:116)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Schedules output (missing schedule for test2.table1):

```
Snapshot as of 2023-04-14 13:44:52
-----------------------------------------------------------------------------------------------------------------------------------------------------------
| Id                                   | Keyspace              | Table              | Status    | Repaired(%) | Completed at        | Next repair         | 
-----------------------------------------------------------------------------------------------------------------------------------------------------------
| 65a162f0-dab3-11ed-8fac-118c57be2947 | test                  | table1             | COMPLETED | 100.00      | 2023-04-14 13:43:29 | 2023-04-14 13:48:29 | 
| 662bc8a0-dab3-11ed-8fac-118c57be2947 | test                  | table2             | COMPLETED | 100.00      | 2023-04-14 13:43:29 | 2023-04-14 13:48:29 | 
| 69bb09e0-dab3-11ed-8fac-118c57be2947 | keyspaceWithCamelCase | tableWithCamelCase | COMPLETED | 100.00      | 2023-04-14 13:43:29 | 2023-04-14 13:48:29 | 
| 67f5b330-dab3-11ed-8fac-118c57be2947 | test2                 | table2             | COMPLETED | 100.00      | 2023-04-14 13:43:29 | 2023-04-14 13:48:29 | 
-----------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by masokol** [comment]
Depending on the solution in #470, it might fix this issue as well.
