### ISSUE TITLE
Flaky unittest TestSubrangeRepairTask.testRepairHalf

### ISSUE THREAD

**Issue by masokol** [Ericsson/ecchronos#512]
The unittest fails sometimes with below

```
Error:  Failures: 
Error:    TestSubrangeRepairTask.testRepairHalf Multiple Failures (2 failures)
	java.lang.AssertionError: 
Expecting:
  <[(1,2], (3,4]]>
to contain exactly (and in same order):
  <[(3,4]]>
but some elements were not expected:
  <[(1,2]]>

	org.mockito.exceptions.verification.NoInteractionsWanted: 
No interactions wanted here:
-> at com.ericsson.bss.cassandra.ecchronos.core.repair.TestSubrangeRepairTask.finalVerification(TestSubrangeRepairTask.java:115)
But found this interaction on mock 'myTableRepairMetrics':
-> at com.ericsson.bss.cassandra.ecchronos.core.repair.RepairTask.execute(RepairTask.java:104)
Actually, above is the only interaction with this mock.
```

**Comment by masokol** [comment]
The #479 refactors the affected code so this might already be fixed. We should wait until it's merged to see if the test is still flaky.

**Comment by masokol** [comment]
Not reproducible. Will reopen if it ever happens again.
