### ISSUE TITLE
Exception in RepairSchedulerImpl#close()

### ISSUE THREAD

**Issue by emolsson** [Ericsson/ecchronos#99]
When closing RepairSchedulerImpl the following exception occurs:
```
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
        at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
        at com.ericsson.bss.cassandra.ecchronos.core.repair.RepairSchedulerImpl.close(RepairSchedulerImpl.java:87)
```

This only happens when the schedule is for multiple tables.

**Comment by emolsson** [comment]
Fixed with PR
